Output neotree.gif
Set Shell zsh
Set Theme "Gruvbox Dark"
Set Margin 60
Set MarginFill "#2dce93"
Set FontSize 20 
Set FontFamily "FiraMono Nerd Font"
Set Width 1200
Set Height 1200
Set Padding 40
# Handle tmux session used for recording 
Hide
Type "tmux kill-session -t neotree"
Enter
Type "tmux new-session -s neotree"
Enter
Show
# Begin Typing command below...
Type "vim ~/Code/argon-portfolio/"
Enter
Sleep 1s
Down 8
Enter
Sleep 2s
Enter
Down 3
Enter
Sleep 2s

